# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for loop

    pod 'FBSDKCoreKit', '~> 4.30'
    pod 'FBSDKShareKit', '~> 4.30'
    pod 'FBSDKLoginKit', '~> 4.30'
    pod 'Bolts', '~> 1.9.0'

  target 'loop-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'loopTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'loop-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
